name: CI

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        name: PHPUnit Tests
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.2', '8.3', '8.4' ]
                symfony: [ false ]
                deps: [ locked ]
                include:
                    -   php: '8.2'
                        deps: lowest
                        deprecations: max[self]=0
                    -   php: '8.4'
                        symfony: '7.4.*'
                        deps: highest
                    -   php: '8.4'
                        deps: highest

        env:
            SYMFONY_REQUIRE: ${{ matrix.symfony }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: zend.exception_ignore_args=false
                    tools: flex

            -   name: Configure composer
                if: "${{ matrix.deps == 'highest' }}"
                run: composer config minimum-stability dev

            -   name: Composer install
                uses: ramsey/composer-install@v3
                with:
                    dependency-versions: '${{ matrix.deps }}'

            -   name: Run tests
                run: vendor/bin/phpunit --coverage-text
