name: CI

on:
    push:
    pull_request:

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        name: Coding Standards
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.4
                    coverage: none
                    tools: php-cs-fixer, cs2pr

            -   name: Run PHP-CS-Fixer
                run: php-cs-fixer fix --dry-run --format checkstyle | cs2pr

    test:
        runs-on: ubuntu-latest
        name: PHPUnit Tests
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.2', '8.3', '8.4' ]
                monolog: [ '3.*' ]
                include:
                    -   php: '8.2'
                        deps: lowest
                        monolog: ''
                        deprecations: max[self]=0
                    -   php: '8.4'
                        deps: highest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: zend.exception_ignore_args=false
                    tools: flex

            -   name: Configure composer
                if: "${{ matrix.deps == 'highest' }}"
                run: composer config minimum-stability dev

            -   name: Require Monolog version
                if: "${{ matrix.monolog != '' }}"
                run: composer require --no-update monolog/monolog:${{ matrix.monolog }}

            -   name: Composer install
                uses: ramsey/composer-install@v3
                with:
                    dependency-versions: '${{ matrix.deps }}'

            -   name: Install PHPUnit dependencies
                run: vendor/bin/simple-phpunit install

            -   name: Run tests
                run: vendor/bin/simple-phpunit -v --coverage-text
                env:
                    SYMFONY_DEPRECATIONS_HELPER: '${{ matrix.deprecations }}'
